[build]
  command = "npm run build"
  publish = "dist/mis-viajes-app/browser"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 